[program:futurebd-queue-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /home/your-user/your-app/artisan queue:work --queue=default --tries=3 --timeout=90 --sleep=3
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=your-user
numprocs=1
redirect_stderr=true
stdout_logfile=/home/your-user/logs/futurebd-queue-worker.log
stopwaitsecs=3600
